services:
  - type: web
    name: bomcore-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:5050"
    envVars:
      - key: FLASK_ENV
        value: development

